# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8d38f5a3d17b7f4f38d3b3851664d4482a2c10ba4df1fc709074f4191c1fd0f9bd18e5afd4e9468e084397c6b9f54f8edd64754fbbd09aa7d8bba02bc2f91a18

test:
  secret_key_base: 4f467b5ef0fe03452a53481386c77a5e540142a0982bf83b460bab7b03f94c2c244a1930e37b14393543efecae9c266098cb4d7730892c4d5c00bb97b49116d8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
